name: Julio Jiménez
favicon: null
layout_spectrum: 0.23433
typography_spectrum: 0.6243945215828717
title: Julio Jiménez
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.9398801638744771
  lightness: 0.939745013602078
  saturation: 0.8256130011286587
  rhythmicContrast: 0.9581488464027643
purpose: []
